use winit::keyboard::KeyCode;
use winit_input_helper::WinitInputHelper;

use crate::machine::generic::keyboard::{KeyCap, KeyboardInput};

const KEYS: &[(KeyCode, KeyCap)] = &[
    (KeyCode::ShiftLeft, KeyCap::LeftShift),
    (KeyCode::ShiftRight, KeyCap::RightShift),
    (KeyCode::ControlLeft, KeyCap::LeftCtrl),
    (KeyCode::ControlRight, KeyCap::RightCtrl),
    (KeyCode::AltLeft, KeyCap::LeftAlt),
    (KeyCode::AltRight, KeyCap::RightAlt),
    (KeyCode::SuperLeft, KeyCap::LeftMeta),
    (KeyCode::SuperRight, KeyCap::RightMeta),
    (KeyCode::CapsLock, KeyCap::CapsLock),
    (KeyCode::Backquote, KeyCap::Grave),
    (KeyCode::Digit1, KeyCap::Digit1),
    (KeyCode::Digit2, KeyCap::Digit2),
    (KeyCode::Digit3, KeyCap::Digit3),
    (KeyCode::Digit4, KeyCap::Digit4),
    (KeyCode::Digit5, KeyCap::Digit5),
    (KeyCode::Digit6, KeyCap::Digit6),
    (KeyCode::Digit7, KeyCap::Digit7),
    (KeyCode::Digit8, KeyCap::Digit8),
    (KeyCode::Digit9, KeyCap::Digit9),
    (KeyCode::Digit0, KeyCap::Digit0),
    (KeyCode::Minus, KeyCap::Minus),
    (KeyCode::Equal, KeyCap::Equal),
    (KeyCode::Backspace, KeyCap::Backspace),
    (KeyCode::Tab, KeyCap::Tab),
    (KeyCode::KeyQ, KeyCap::Q),
    (KeyCode::KeyW, KeyCap::W),
    (KeyCode::KeyE, KeyCap::E),
    (KeyCode::KeyR, KeyCap::R),
    (KeyCode::KeyT, KeyCap::T),
    (KeyCode::KeyY, KeyCap::Y),
    (KeyCode::KeyU, KeyCap::U),
    (KeyCode::KeyI, KeyCap::I),
    (KeyCode::KeyO, KeyCap::O),
    (KeyCode::KeyP, KeyCap::P),
    (KeyCode::BracketLeft, KeyCap::LeftBracket),
    (KeyCode::BracketRight, KeyCap::RightBracket),
    (KeyCode::Backslash, KeyCap::Backslash),
    (KeyCode::KeyA, KeyCap::A),
    (KeyCode::KeyS, KeyCap::S),
    (KeyCode::KeyD, KeyCap::D),
    (KeyCode::KeyF, KeyCap::F),
    (KeyCode::KeyG, KeyCap::G),
    (KeyCode::KeyH, KeyCap::H),
    (KeyCode::KeyJ, KeyCap::J),
    (KeyCode::KeyK, KeyCap::K),
    (KeyCode::KeyL, KeyCap::L),
    (KeyCode::Semicolon, KeyCap::Semicolon),
    (KeyCode::Quote, KeyCap::Quote),
    (KeyCode::Enter, KeyCap::Enter),
    (KeyCode::IntlBackslash, KeyCap::LessGreater),
    (KeyCode::KeyZ, KeyCap::Z),
    (KeyCode::KeyX, KeyCap::X),
    (KeyCode::KeyC, KeyCap::C),
    (KeyCode::KeyV, KeyCap::V),
    (KeyCode::KeyB, KeyCap::B),
    (KeyCode::KeyN, KeyCap::N),
    (KeyCode::KeyM, KeyCap::M),
    (KeyCode::Comma, KeyCap::Comma),
    (KeyCode::Period, KeyCap::Period),
    (KeyCode::Slash, KeyCap::Slash),
    (KeyCode::Space, KeyCap::Space),
    (KeyCode::ContextMenu, KeyCap::Menu),
    (KeyCode::Escape, KeyCap::Escape),
    (KeyCode::F1, KeyCap::F1),
    (KeyCode::F2, KeyCap::F2),
    (KeyCode::F3, KeyCap::F3),
    (KeyCode::F4, KeyCap::F4),
    (KeyCode::F5, KeyCap::F5),
    (KeyCode::F6, KeyCap::F6),
    (KeyCode::F7, KeyCap::F7),
    (KeyCode::F8, KeyCap::F8),
    (KeyCode::F9, KeyCap::F9),
    (KeyCode::F10, KeyCap::F10),
    (KeyCode::F11, KeyCap::F11),
    (KeyCode::F12, KeyCap::F12),
    (KeyCode::F13, KeyCap::F13),
    (KeyCode::F14, KeyCap::F14),
    (KeyCode::F15, KeyCap::Help),
    (KeyCode::Help, KeyCap::Help),
    (KeyCode::F16, KeyCap::Do),
    (KeyCode::F17, KeyCap::F17),
    (KeyCode::F18, KeyCap::F18),
    (KeyCode::F19, KeyCap::F19),
    (KeyCode::F20, KeyCap::F20),
    (KeyCode::PrintScreen, KeyCap::PrintScreen),
    (KeyCode::ScrollLock, KeyCap::ScrollLock),
    (KeyCode::Pause, KeyCap::Pause),
    (KeyCode::Insert, KeyCap::Insert),
    (KeyCode::Home, KeyCap::Home),
    (KeyCode::PageUp, KeyCap::PageUp),
    (KeyCode::Delete, KeyCap::Delete),
    (KeyCode::End, KeyCap::End),
    (KeyCode::PageDown, KeyCap::PageDown),
    (KeyCode::ArrowUp, KeyCap::Up),
    (KeyCode::ArrowDown, KeyCap::Down),
    (KeyCode::ArrowLeft, KeyCap::Left),
    (KeyCode::ArrowRight, KeyCap::Right),
    (KeyCode::NumLock, KeyCap::NumLock),
    (KeyCode::NumpadDivide, KeyCap::KpDivide),
    (KeyCode::NumpadMultiply, KeyCap::KpMultiply),
    (KeyCode::NumpadSubtract, KeyCap::KpMinus),
    (KeyCode::NumpadAdd, KeyCap::KpPlus),
    (KeyCode::NumpadEnter, KeyCap::KpEnter),
    (KeyCode::NumpadDecimal, KeyCap::KpPeriod),
    (KeyCode::NumpadComma, KeyCap::KpComma),
    (KeyCode::Numpad0, KeyCap::Kp0),
    (KeyCode::Numpad1, KeyCap::Kp1),
    (KeyCode::Numpad2, KeyCap::Kp2),
    (KeyCode::Numpad3, KeyCap::Kp3),
    (KeyCode::Numpad4, KeyCap::Kp4),
    (KeyCode::Numpad5, KeyCap::Kp5),
    (KeyCode::Numpad6, KeyCap::Kp6),
    (KeyCode::Numpad7, KeyCap::Kp7),
    (KeyCode::Numpad8, KeyCap::Kp8),
    (KeyCode::Numpad9, KeyCap::Kp9),
];

pub fn update_keyboard(input: &WinitInputHelper, keyboard: &mut dyn KeyboardInput) {
    for &(code, cap) in KEYS {
        if input.key_pressed_os(code) {
            keyboard.key_down(cap);
        }
    }
    for &(code, cap) in KEYS {
        if input.key_released(code) {
            keyboard.key_up(cap);
        }
    }
}
